spring.application.name=reddit-spring-boot-sample


reddit.user-agent=SpringBootRedditStarter:v1.0.0 (by /u/springboot)
reddit.default-subreddit=java
reddit.default-limit=25

server.port=8080

logging.level.org.example=DEBUG