spring.application.name=reddit-spring-boot-autoconfigure


reddit.user-agent=MyApp:v1.0.0 (by /u/myusername)
reddit.default-subreddit=programming
reddit.default-limit=50
reddit.connect-timeout=10000
reddit.read-timeout=10000